apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rentacar
    version: "1.0"
  name: rentacar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rentacar
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rentacar
    spec:
      containers:
        - name: rentacar
          image: toscy/rentacar:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rentacar
  name: rentacar
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: rentacar
  type: LoadBalancer
status:
  loadBalancer: {}
